-- Modo Terapia Convencional (#98): UM valor novo no enum de subtipo de
-- extração, carregando o objeto inteiro do contrato TC no `payload` jsonb que
-- já existe. Não há tabela nova, coluna nova nem backfill — migração aditiva.
--
-- Por que um único valor, e não um por campo do contrato TC: `trecho_fonte` e
-- `confianca` são NOT NULL em `extraction`, e o contrato TC não tem eixo de
-- confiança nem um trecho único que sustente `resumo_sessao` ou
-- `padrao_participacao_verbal.presente = false`.
--
-- Sem GRANT novo: o grant é por COLUNA em `extraction` e nenhuma coluna muda —
-- só o domínio de um enum já concedido.
ALTER TYPE "public"."extraction_subtipo" ADD VALUE 'resumo_terapia_convencional' BEFORE 'pendente';
