allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - prettier@3.9.5
  - '@storybook/addon-a11y@10.5.3'
  - '@storybook/addon-docs@10.5.3'
  - '@storybook/addon-vitest@10.5.3'
  - '@storybook/builder-vite@10.5.3'
  - '@storybook/csf-plugin@10.5.3'
  - '@storybook/nextjs-vite@10.5.3'
  - '@storybook/react-dom-shim@10.5.3'
  - '@storybook/react-vite@10.5.3'
  - '@storybook/react@10.5.3'
  - eslint-plugin-storybook@10.5.3
  - storybook@10.5.3
